# Generated by Django 4.2.30 on 2026-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_seed_servicios_barrio_claro'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido_texto',
            field=models.TextField(blank=True, editable=False, help_text='Texto extraído del archivo, usado como contexto del chatbot de KMDB.'),
        ),
    ]
