# Generated by Django 4.2.30 on 2026-08-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_documento_contenido_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(help_text='Texto libre que se suma al contexto del chatbot de KMDB.')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contexto para IA',
                'verbose_name_plural': 'Contextos para IA',
                'ordering': ['-creado'],
            },
        ),
    ]
